[package]
name = "solana-test-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.15.2"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-test-validator"
readme = "../README.md"
repository = "https://github.com/solana-labs/solana"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
log = "0.4.17"
serde_derive = "1.0.103"
serde_json = "1.0.83"
solana-cli-output = { path = "../cli-output", version = "=1.15.2" }
solana-client = { path = "../client", version = "=1.15.2" }
solana-core = { path = "../core", version = "=1.15.2" }
solana-gossip = { path = "../gossip", version = "=1.15.2" }
solana-ledger = { path = "../ledger", version = "=1.15.2" }
solana-logger = { path = "../logger", version = "=1.15.2" }
solana-net-utils = { path = "../net-utils", version = "=1.15.2" }
solana-program-runtime = { path = "../program-runtime", version = "=1.15.2" }
solana-program-test = { path = "../program-test", version = "=1.15.2" }
solana-rpc = { path = "../rpc", version = "=1.15.2" }
solana-rpc-client = { path = "../rpc-client", version = "=1.15.2", default-features = false }
solana-runtime = { path = "../runtime", version = "=1.15.2" }
solana-sdk = { path = "../sdk", version = "=1.15.2" }
solana-streamer = { path = "../streamer", version = "=1.15.2" }
solana-tpu-client = { path = "../tpu-client", version = "=1.15.2", default-features = false }
tokio = { version = "1", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
